name: commsensomobile
description: "App mobile projeto commsenso."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Utility Packages
  http: ^1.1.0
  mqtt_client: ^9.6.1
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^8.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/commsenso_icon.png
    - assets/icons/commsenso_logo_sem_fundo.png
    - assets/animations/

flutter_native_splash:
  color: "#FFFFFF"                   # fundo do tema claro
  image: assets/images/logo/commsenso_logo_sem_fundo.png    # logo central

  android_12:                        # exigência do Android 12+
    color: "#FFFFFF"
    image: assets/images/logo/commsenso_logo_sem_fundo.png

  web: false

flutter_launcher_icons:
  android: "adaptive"                   # gera ícone adaptativo (Android 8+)
  ios: true
  image_path: assets/icons/commsenso_icon.png # base única p/ ambas as plataformas

  # Android adaptativo (opcional, mas recomendado):
  adaptive_icon_foreground: assets/icons/commsenso_icon.png
  adaptive_icon_background: "#FFFFFF"   # pode ser uma cor ou uma imagem
  # Android 13 (monocromático, opcional):
  # adaptive_icon_monochrome: assets/icons/app_icon_mono.png

  # iOS:
  remove_alpha_ios: true                # iOS não gosta de transparência no ícone
  min_sdk_android: 21
